### ISSUE TITLE
Review request 

### ISSUE THREAD

**Issue by anodaini** [UBC-MDS/sptidy#36]
Submitting Author: Jacob McFarlane @JacobMcFarlane, Asma Al-Odaini (@anodaini), Xudong Yang @xudongyang2, Heidi Ye @heidi-ye
Repository: [sptidy](https://github.com/UBC-MDS/sptidy)
Version submitted: 0.2.0
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: sptidy
Title: Tidy-up linear regression and kmeans model outputs
Version: 0.0.0.9000
Authors@R: 
    c(person(given = "Jacob",
           family = "McFarlane",
           role = c("aut", "cre"),
           email = "jacob@jakenow.net"),
    person(given = "Asma",
           family = "Al-Odaini",
           role = c("aut")),
    person(given = "Peter",
           family = "Yang",
           role = c("aut")),
    person(given = "Heidi",
           family = "Ye",
           role = c("aut"))
           )
Description: Sptidy implements a tidy and augment function for base R’s linear regression and Tidymodel’s kmeans clustering to ease model selection and assessment tasks. This package is a simplified reimplementation of the existing tidy and augments functions in the Broom package. Sptidy’s family of tidy functions returns a dataframe that summarizes important model information, while the augment function expands the original dataframe to include additional model specific information by observation. This package is meant to complement Sktidy, a Python package that was created to tidy up the scikit-learn package.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
Suggests: 
    testthat (>= 3.0.0),
    covr
Config/testthat/edition: 3
URL: https://github.com/UBC-MDS/sptidy
BugReports: https://github.com/UBC-MDS/sptidy/issues
Imports: 
    tibble,
    dplyr,
    broom

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [x] data extraction
	- [x] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
> The package falls under data extraction because it retrieves data from the models and presents it in a structured way. In addition, it falls under data munging because it transforms the data into a more accessible and appropriate form. 

-   Who is the target audience and what are scientific applications of this package?
>  The target audience would be people that want to use a lightweight package that outputs a tidy dataframe of the `kmeans` and `lm` models from the `stats` package. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
> The `sptidy` packages implements functionality that closely resembles the `broom`'s package `tidy()` and `augment()` functions for the `lm` and `kmeans` model. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [ ] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [ ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by anodaini** [comment]
Hi team, please review my answers for the target audience and for overlapping with existing R packages. Thank you!

**Comment by heidi-ye** [comment]
This looks good to me! I guess we don't technically have the vignette ready but I assume it'll be fine by the time we are ready for submission.

**Comment by xudong-Y** [comment]
Looks good!

**Comment by anodaini** [comment]
We might want to update the description line of the description file. 
> Description: What the package does (one paragraph).

Also @JacobMcFarlane I believe you set up the repo and the package. Is there a reason why you have the URL and bug reports in the description file of the repo as your personal repo and not (https://github.com/UBC-MDS/sptidy)? 

Taken care of #40 #38
